/**
 *               __     __
 * .-----.-----.|__|.--|  |.-----.--.--.
 * |__ --|  _  ||  ||  _  ||  -__|  |  |
 * |_____|   __||__||_____||_____|___  |
 *       |__|                    |_____|
 *
 * SPIDEY v0.2.1
 *
 * Copyright (C) 2013 Fabio Cicerchia <info@fabiocicerchia.it>
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

var casper   = casper || {},
    fs       = require('fs'),
    srcdir   = fs.absolute('.') + (casper.cli.has('coverage') ? '/src-cov' : '/src'),
    glob     = require(srcdir + '/glob'),
    basePath = fs.absolute('.') + '/test/assets/';

casper.options.onPageInitialized = function () {
    casper.page.injectJs(srcdir + '/sha1.js');
    casper.page.injectJs(srcdir + '/events.js');
};

casper.on('remote.message', function (msg) {
    console.log('CONSOLE.LOG: ' + msg);
});

casper.test.begin('Test', function (test) {
    var Test      = require(srcdir + '/test'),
        fsWrapper = new (require(srcdir + '/fs'))(fs),
        testObj   = new Test(fsWrapper, glob, srcdir + '/..');

    // create
    testObj.create('', 'test', {a: 1}, function () {
        var content;
        try {
            content = fs.read(srcdir + '/..' + testObj.TEST_CASE_DIRECTORY + 'test.tst');
        } catch (ignore) {}

        test.assertEquals(content, undefined, 'doesn\'t create a file if url is empty');
    });

    testObj.create('http://www.example.com', '', {a: 1}, function () {
        var content;
        try {
            content = fs.read(srcdir + '/..' + testObj.TEST_CASE_DIRECTORY + 'http___www_example_com/.tst');
        } catch (ignore) {}

        test.assertEquals(content, undefined, 'doesn\'t create a file if name is empty');
    });

    testObj = new Test(fsWrapper, glob, srcdir + '/..');
    testObj.create('http://www.example.com', 'test', {}, function () {
        var content;
        try {
            content = fs.read(srcdir + '/..' + testObj.TEST_CASE_DIRECTORY + 'http___www_example_com/test.tst');
        } catch (ignore) {}

        test.assertEquals(content, undefined, 'doesn\'t create a file if data is empty');
    });

    testObj = new Test(fsWrapper, glob, srcdir + '/..');
    testObj.create('http://www.example.com', 'test', {a: 1, b: 2}, function () {
        var content;
        try {
            content = fs.read(srcdir + '/..' + testObj.TEST_CASE_DIRECTORY + 'http___www_example_com/test.tst');
            fs.remove(srcdir + '/..' + testObj.TEST_CASE_DIRECTORY + 'http___www_example_com/test.tst');
        } catch (ignore) {}

        test.assertMatch(content, /; Test Case File\n; generated by Spidey v.+ \(.+\) at /);
        test.assertMatch(content, /\n; url = http:\/\/www.example.com\n; id = test\n\n\[POST\]\na=1\nb=2\n/, 'creates a file if url, name and data is not empty');
    });

    // getCases
    testObj = new Test(fsWrapper, glob, srcdir + '/..');
    testObj.parseCase = function () { return {}; };

    test.assertEquals(testObj.getCases(''), [], 'doesn\'t return anything if there are no matches');
    test.assertEquals(testObj.getCases('non-existent'), [], 'doesn\'t return anything if there are no matches');

    fs.write(srcdir + '/..' + testObj.TEST_CASE_DIRECTORY + 'http___www_example_com/test.tst', 'a=1\nb=2\n');
    testObj = new Test(fsWrapper, glob, srcdir + '/..');
    testObj.parseCase = function () { return {a: 1, b: 2}; };

    test.assertEquals(testObj.getCases('http___www_example_com'), [{a: 1, b: 2}], 'returns something if there are matches');
    fs.remove(srcdir + '/..' + testObj.TEST_CASE_DIRECTORY + 'http___www_example_com/test.tst');

    // parseCase
    testObj = new Test(fsWrapper, glob, srcdir + '/..');
    test.assertEquals(testObj.parseCase('non-existent'), {}, 'doesn\'t parse a non existent file');

    testObj = new Test(fsWrapper, glob, srcdir + '/..');
    test.assertEquals(testObj.parseCase('empty-file'), {}, 'parses an empty file');

    testObj = new Test(fsWrapper, glob, srcdir + '/..');
    fs.write(srcdir + '/..' + testObj.TEST_CASE_DIRECTORY + 'not-empty-file.tst', 'a=1\nb=2\n');
    test.assertEquals(testObj.parseCase(srcdir + '/..' + testObj.TEST_CASE_DIRECTORY + 'not-empty-file.tst'), {a: '1', b: '2'}, 'parses a not empty file');
    fs.remove(srcdir + '/..' + testObj.TEST_CASE_DIRECTORY + 'not-empty-file.tst');

    fs.removeTree(srcdir + '/..' + testObj.TEST_CASE_DIRECTORY + 'http___www_example_com');

    test.done();
});