language: node_js

node_js:
  - "0.11"
  - "0.10"
  - "0.8"

branches:
  only:
    - develop
    - master

before_install:
  - sudo apt-get update -qq

script:
  - make versions
  - npm --registry http://registry.npmjs.eu/ install
  - make install
  - npm test
  - make coverage
