language: node_js

node_js:
  - "0.11"
  - "0.10"
  - "0.8"
  - "0.6"

branches:
  only:
    - develop
    - master

script:
  - make install-casper
  - npm --registry http://registry.npmjs.eu/ install
  - npm test
