#!/bin/bash
[ $(./bin/crawler --url "tests/test_01.html" | grep "Launching crawler #" | wc -l) -eq "1" ] && echo "true" || echo "false"
[ $(./bin/crawler --url "tests/test_02.html" | grep "Launching crawler #" | wc -l) -eq "2" ] && echo "true" || echo "false"
[ $(./bin/crawler --url "tests/test_03.html" | grep "Launching crawler #" | wc -l) -eq "2" ] && echo "true" || echo "false"
[ $(./bin/crawler --url "tests/test_04.html" | grep "Launching crawler #" | wc -l) -eq "2" ] && echo "true" || echo "false"
[ $(./bin/crawler --url "tests/test_05.html" | grep "Launching crawler #" | wc -l) -eq "2" ] && echo "true" || echo "false"
[ $(./bin/crawler --url "tests/test_06.html" | grep "Launching crawler #" | wc -l) -eq "1" ] && echo "true" || echo "false"
[ $(./bin/crawler --url "tests/test_07.html" | grep "Launching crawler #" | wc -l) -eq "1" ] && echo "true" || echo "false"
[ $(./bin/crawler --url "tests/test_08.html" | grep "Launching crawler #" | wc -l) -eq "1" ] && echo "true" || echo "false"
[ $(./bin/crawler --url "tests/test_09.html" | grep "Launching crawler #" | wc -l) -eq "1" ] && echo "true" || echo "false"
[ $(./bin/crawler --url "tests/test_10.html" | grep "Launching crawler #" | wc -l) -eq "1" ] && echo "true" || echo "false"
[ $(./bin/crawler --url "tests/test_11.html" | grep "Launching crawler #" | wc -l) -eq "1" ] && echo "true" || echo "false"
[ $(./bin/crawler --url "tests/test_12.html" | grep "Launching crawler #" | wc -l) -eq "1" ] && echo "true" || echo "false"
[ $(./bin/crawler --url "tests/test_13.html" | grep "Launching crawler #" | wc -l) -eq "1" ] && echo "true" || echo "false"